### ISSUE TITLE
Consider adding a warning about missing rule sets semi colon 

### ISSUE THREAD

**Issue by pascalduez** [pascalduez/postcss-apply#19]
In a native environment this will break.

```css
.foo {
  --bar: {
    color: red;
  }
  border: none;
}
```
