### ISSUE TITLE
Nested mixins

### ISSUE THREAD

**Issue by JosefJezek** [pascalduez/postcss-apply#3]
Could you add support for nested mixins?

```css
--paper-font-common-base: {
  font-family: 'Roboto', 'Noto', sans-serif;
  -webkit-font-smoothing: antialiased;
};

--paper-font-common-nowrap: {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
};

--paper-font-title: {
  @apply --paper-font-common-base;
  @apply --paper-font-common-nowrap;

  font-size: 20px;
  font-weight: 500;
  line-height: 28px;
};

.Skeleton-drawerTitle {
  @apply --paper-font-title;
}
```

Bad output

```css
.Skeleton-drawerTitle {
  @apply --paper-font-common-base;
  @apply --paper-font-common-nowrap;
  font-size: 20px;
  font-weight: 500;
  line-height: 28px;
}
```
