### ISSUE TITLE
The @apply rule can only be declared inside Rule type nodes?

### ISSUE THREAD

**Issue by jonathantneal** [pascalduez/postcss-apply#32]
previously valid usage alongside css nesting:

```css
.excerpt-of-my-component {
	background-color: var(--mono-97);

	@media (--screen-ml) {
		@apply --submenu-styles;

		display: flex;
		flex-wrap: wrap;
		padding-top: 48px;
	}
}
```

I now get the error:

```
The @apply rule can only be declared inside Rule type nodes.
```

Another (made-up) but very possible example

```css
.excerpt-of-my-component {
	@nest [dir="rtl"] & {
		@apply --rtl-behavior-styles;
	}
}
```

Could this plugin search for an ancestor rule rather than a parent rule?
