### ISSUE TITLE
@apply rule with brackets

### ISSUE THREAD

**Issue by JosefJezek** [pascalduez/postcss-apply#4]
Could you add support for `@apply` rule with brackets?

```css
    /* Shared Styles */
    --paper-font-common-base: {
      font-family: 'Roboto', 'Noto', sans-serif;
      -webkit-font-smoothing: antialiased;
    };
    --paper-font-common-nowrap: {
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    };
    /* Material Font Styles */
    --paper-font-display4: {
      @apply(--paper-font-common-base);
      @apply(--paper-font-common-nowrap);
      font-size: 112px;
      font-weight: 300;
      letter-spacing: -.044em;
      line-height: 120px;
    };
```

I need this brackets for Polymer `@apply` rule, check out this links
- https://github.com/PolymerElements/paper-styles/blob/master/typography.html
- https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins

@robdodson Why Polymer have `@apply` rule with brackets? Proposal of `@apply` rule have not brackets, check out this link http://tabatkins.github.io/specs/css-apply-rule/
